quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=Password09
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:54325/postgres?currentSchema=fleet_gps_tracking_schema

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true